format = """
$time \
$os\
$username\
$directory\
$git_branch\
$git_status\
$conda\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$package\
$docker_context\
"""

# Inserts a blank line between shell prompts
add_newline = false

# Change command timeout from 500 to 1000 ms
command_timeout = 1000

# Change the default prompt format
#format = """$env_var $all"""

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[âœ](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'
error_symbol = '[âœ—](bold red)' # The 'error_symbol' segment is being set to 'âœ—' with the color 'bold red'

# Shows an icon that should be included by zshrc script based on the distribution or os
[env_var.STARSHIP_DISTRO]
format = '[$env_value](white)'
variable = "STARSHIP_DISTRO"
disabled = false

# Shows the username
[username]
style_user = "fg:#F7879A"
style_root = "fg:#F7879A"
format = "USER: [$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = true
format = "on [$hostname](blue) "
disabled = true

[directory]
style = "fg:#DA627D"
#format = "[ $path ]($style)"
format = "at [$path]($style)[$read_only]($read_only_style) "
truncation_length = 1
truncation_symbol = "â†³/"
use_os_path_sep = true
read_only = "ğŸ”’"
#home_symbol = " ğŸ  ~"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
#"Documents" = " ğŸ“‚ Documents"
#"Downloads" = " ğŸ“¥ Downloads"
#"Music" = " ğŸ§ Music"
#"Pictures" = " ğŸ“· Pictures"
#"Videos" = " ğŸï¸ Videos"
#"Applications" = " ğŸš€ Applications"
#"Desktop" = " ğŸ–¥ï¸ Desktop"
"Playground" = 'ï–• Playground'
"GitHub" = "ï£ GitHub"
"GitLab" = "ï¡ GitLab"
"Developer" = "ï„¡ Developer"

[git_branch]
symbol = "ï¡ "
format = "| [$symbol$branch]($style) "
# truncation_length = 4
truncation_symbol = "â€¦/"
style = "fg:#FCA17D"

[git_status]
format = '[$all_status$ahead_behind]($style) '
style = "fg:#FCA17D"
conflicted = "ğŸ³"
up_to_date = "ï† "
untracked = "ï”© "
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
stashed = "ï£– "
modified = "ï„ "
staged = '[++\($count\)](green)'
renamed = "ïª¶ "
deleted = "ï€” "

[conda]
symbol = "ïš¦"
ignore_base = false
style = "fg:#86BBD8"
format = 'on [$symbol $environment ]($style)'

[kubernetes]
format = 'via [ï´± $context\($namespace\)](bold purple) '
disabled = false

# (deactivated because of no space left)
[terraform]
format = "via [ï„µ terraform $version]($style) ï¥‚ [$workspace]($style) "
disabled = false

[vagrant]
format = "via [ï„µ vagrant $version]($style) "
disabled = true

[docker_context]
format = "via [ïŒˆ $context](bold blue) "
disabled = false

[helm]
format = "via [ïˆš $version](bold purple) "
disabled = true

[python]
symbol = "ï Ÿ "
python_binary = "python3"
disabled = true

[nodejs]
format = "via [ï¢˜ $version](bold green) "
disabled = false

[ruby]
format = "via [îˆ¾ $version]($style) "
disabled = true

# ~/.config/starship.toml

[azure]
disabled = true
format = "on [$symbol($username)]($style) "
symbol = "ó° … "
style = "blue bold"

# ~/.config/starship.toml

[aws]
format = 'on [$symbol$region]($style) '
style = 'bold blue'
symbol = 'ğŸ…° '
disabled = true

[gcloud]
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '
disabled = true

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#FFFFFF"
format = 'ğŸ± \[$time\]($style)'